#!/bin/bash

# Update umask to retain group write permissions on runtime directories: $root/tmp/default, $root/logs/default and $root/run/default
umask 0007

set -eo pipefail

# If ELASTICSEARCH_CONFIG if set, preprend the -c parameter to the paramers array
if [[ -n "$ELASTICSEARCH_CONFIG" ]]; then
    # Prepend "-c $ELASTICSEARCH_CONFIG" to the arguments array
    set -- "-c" "$ELASTICSEARCH_CONFIG" "$@"
fi

# For information on the possible environment variables that can be passed into the container. Run the following
# command for information on the options that are available.
#
# `./elastic-agent container --help`
#

echo "Running elastic-agent container $@"

exec elastic-agent container "$@"
